name: Continuous Integration

on:
  - push
  - pull_request

jobs:
  continuous-integration:
    strategy:
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: rm .swift-version
      - name: Install Swift
        uses: YOCKOW/Action-setup-swift@v1
        with:
          swift-version: '5.9'
      - name: Test
        run: swift test --enable-test-discovery
